karpenter:
  serviceAccount:
    create: false
  nodeSelector:
    kubernetes.io/os: linux
  settings:
      clusterName:
      clusterEndpoint:
      defaultInstanceProfile:
      interruptionQueueName:
